### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/RestRepo#2]
## General Items
- [x] It has a github repo
- [x] It has a proper Apache2 LICENSE file
- [ ] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [ ] It's tested
- [x] It's hooked to the [open-source hipchat room](http://inaka.net/hipchat)
- [ ] It has a link to the [open-source hipchat room](http://inaka.net/hipchat) in its README
- [ ] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page

## Exhibition
- [ ] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description
- [ ] It has a landing page built in github pages

## For Libraries
- [ ] It provides a sample application
- [ ] Examples of use are documented in the README or linked from there

## For Erlang/Elixir Projects
- [ ] It's shared on [Erlang Central](http://erlangcentral.org/add-news/)
- [ ] It's published on [Hex.pm](https://hex.pm)
